spring:
  datasource:
    url: jdbc:mysql://localhost:3306/alurafood-pedidos?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: pedidos-ms

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    # Gera um ID único para cada instância do serviço
    instance-id: ${spring.application.name}:${random.int}
    # Diz ao Eureka para preferir registrar o endereço IP em vez do hostname
    prefer-ip-address: true
    # Define manualmente o hostname
    hostname: localhost

# MS irá subir numa porta aleatória
server:
  port: 0